apiVersion: v1
kind: Namespace
metadata:
  name: rlhf-contracts
  labels:
    name: rlhf-contracts
    tier: production
---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: rlhf-contracts
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: rlhf-contracts
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "4"